# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

environment:
  GITHUB_PAT:
    secure: Zdu+XV+DvPEzUyw+7o0AjzmOqvNAV8drbQrJr/kZ2+ZnzR80CQ5xz4FMLSEdllEq
  docuSign_username:
    secure: KUq95zYgr6zn5WuzdIdjXUk62cDeTB5q5K/+27pnHxQ=
  docuSign_password:
    secure: uSOKSOqjTYqVMJSuA1mWRQ==
  docuSign_integrator_key:
    secure: Rx7t1EBD6Oz+RY2i8hHJZF3Gh6RkzCf8x0RWgDkAp/9jDZKoMLAR7LUbtqi89xlY